import { Product, Review, User } from '@/types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Tech Organizer Stand',
    description: 'Sleek desk organizer for your devices and accessories',
    price: 24.99,
    rating: 4.8,
    reviewCount: 25,
    imageSrc: '/images/products/organizer.jpg',
    imageAlt: 'Tech organizer stand in black material',
    category: 'functional',
    featured: true,
    inStock: true,
    newArrival: false,
    details: 'This tech organizer stand is designed to keep your desk tidy and your devices accessible. It features compartments for your phone, tablet, headphones, and other accessories.',
    specs: {
      dimensions: '10" x 6" x 4"',
      weight: '0.5 lbs',
      material: 'PLA Plastic',
      color: 'Matte Black',
    },
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2023-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Phoenix Art Sculpture',
    description: 'Detailed phoenix sculpture with intricate designs',
    price: 29.99,
    rating: 5.0,
    reviewCount: 12,
    imageSrc: '/images/products/phoenix.jpg',
    imageAlt: 'Phoenix sculpture with detailed wing features',
    category: 'art',
    featured: true,
    inStock: true,
    newArrival: true,
    details: 'This intricate phoenix sculpture showcases the majestic mythical bird rising from the ashes. Each feather is carefully designed to create a stunning display piece for your home or office.',
    specs: {
      dimensions: '8" x 6" x 10"',
      weight: '0.8 lbs',
      material: 'PETG Plastic',
      color: 'Iridescent Red/Gold',
    },
    createdAt: '2023-03-10T00:00:00Z',
    updatedAt: '2023-03-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Geometric Lamp Shade',
    description: 'Modern lamp shade with geometric patterns',
    price: 18.50,
    rating: 4.5,
    reviewCount: 18,
    imageSrc: '/images/products/lampshade.jpg',
    imageAlt: 'Geometric lamp shade with tessellated pattern',
    category: 'functional',
    featured: true,
    inStock: true,
    newArrival: false,
    details: 'Transform your living space with this modern geometric lamp shade. The intricate patterns create beautiful light and shadow effects when illuminated.',
    specs: {
      dimensions: '8" diameter x 9" height',
      weight: '0.3 lbs',
      material: 'PLA Plastic',
      color: 'White/Translucent',
    },
    createdAt: '2023-02-05T00:00:00Z',
    updatedAt: '2023-02-05T00:00:00Z',
  },
  {
    id: '4',
    name: 'Futuristic Planter',
    description: 'Self-watering planter with modern design',
    price: 15.99,
    rating: 4.2,
    reviewCount: 32,
    imageSrc: '/images/products/planter.jpg',
    imageAlt: 'Modern self-watering planter in silver finish',
    category: 'functional',
    featured: true,
    inStock: true,
    newArrival: false,
    details: 'This futuristic self-watering planter is perfect for busy plant lovers. The reservoir at the bottom ensures your plants get just the right amount of water.',
    specs: {
      dimensions: '6" x 6" x 7"',
      weight: '0.6 lbs',
      material: 'PLA Plastic',
      color: 'Silver/Metallic',
    },
    createdAt: '2023-01-20T00:00:00Z',
    updatedAt: '2023-01-20T00:00:00Z',
  },
  {
    id: '5',
    name: 'Desktop Cable Organizer',
    description: 'Keep your workspace tidy with this sleek cable organizer',
    price: 12.99,
    rating: 4.6,
    reviewCount: 42,
    imageSrc: '/images/products/cable-organizer.jpg',
    imageAlt: 'Desktop cable organizer with multiple slots',
    category: 'functional',
    featured: false,
    inStock: true,
    newArrival: true,
    details: 'This desktop cable organizer features multiple slots to keep your charging cables, headphone wires, and other cords neatly arranged and easily accessible.',
    specs: {
      dimensions: '5" x 3" x 1"',
      weight: '0.2 lbs',
      material: 'PLA Plastic',
      color: 'Black/Gray',
    },
    createdAt: '2023-04-10T00:00:00Z',
    updatedAt: '2023-04-10T00:00:00Z',
  },
  {
    id: '6',
    name: 'Abstract Wave Sculpture',
    description: 'Elegant wave-inspired art piece for modern decor',
    price: 34.99,
    rating: 4.9,
    reviewCount: 15,
    imageSrc: '/images/products/wave-sculpture.jpg',
    imageAlt: 'Abstract wave sculpture in blue gradient',
    category: 'art',
    featured: false,
    inStock: true,
    newArrival: true,
    details: 'This abstract wave sculpture draws inspiration from ocean movements. The flowing design and gradient coloring create a calming focal point for any room.',
    specs: {
      dimensions: '12" x 5" x 8"',
      weight: '0.7 lbs',
      material: 'PETG Plastic',
      color: 'Blue Gradient',
    },
    createdAt: '2023-04-20T00:00:00Z',
    updatedAt: '2023-04-20T00:00:00Z',
  },
  {
    id: '7',
    name: 'Smartphone Amplifier Stand',
    description: 'Passive amplifier that boosts your phone\'s sound naturally',
    price: 19.99,
    rating: 4.3,
    reviewCount: 28,
    imageSrc: '/images/products/phone-amplifier.jpg',
    imageAlt: 'Smartphone amplifier stand with acoustic chamber',
    category: 'functional',
    featured: false,
    inStock: true,
    newArrival: false,
    details: 'This passive smartphone amplifier uses acoustic principles to naturally boost your phone\'s volume without electronics or batteries. Perfect for watching videos or listening to music.',
    specs: {
      dimensions: '6" x 4" x 3"',
      weight: '0.4 lbs',
      material: 'PLA Plastic',
      color: 'Matte Black',
    },
    createdAt: '2023-02-15T00:00:00Z',
    updatedAt: '2023-02-15T00:00:00Z',
  },
  {
    id: '8',
    name: 'Geometric Bookends',
    description: 'Modern bookends with sacred geometry patterns',
    price: 22.99,
    rating: 4.7,
    reviewCount: 19,
    imageSrc: '/images/products/bookends.jpg',
    imageAlt: 'Geometric bookends with sacred geometry pattern',
    category: 'functional',
    featured: false,
    inStock: true,
    newArrival: false,
    details: 'These geometric bookends feature sacred geometry patterns that add a touch of modern elegance to your bookshelf. Weighted for stability and designed to complement any decor style.',
    specs: {
      dimensions: '6" x 4" x 6" (each)',
      weight: '1.2 lbs (pair)',
      material: 'PLA Plastic with Metal Weights',
      color: 'Black/Gold',
    },
    createdAt: '2023-01-05T00:00:00Z',
    updatedAt: '2023-01-05T00:00:00Z',
  },
]

export const mockReviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userId: '101',
    userName: 'Sarah Johnson',
    userImage: '/images/testimonials/sarah.jpg',
    rating: 5,
    title: 'Perfect for my workspace!',
    content: 'This organizer has transformed my desk from cluttered to clean. The build quality is excellent and it fits all my devices perfectly.',
    createdAt: '2023-03-15T00:00:00Z',
    updatedAt: '2023-03-15T00:00:00Z',
  },
  {
    id: '2',
    productId: '1',
    userId: '102',
    userName: 'Michael Chen',
    userImage: '/images/testimonials/michael.jpg',
    rating: 4,
    title: 'Good quality but a bit small',
    content: 'The organizer is well-made and looks great on my desk. My only complaint is that it\'s slightly smaller than I expected, but it still works well for my basic needs.',
    createdAt: '2023-04-02T00:00:00Z',
    updatedAt: '2023-04-02T00:00:00Z',
  },
  {
    id: '3',
    productId: '2',
    userId: '103',
    userName: 'Emma Rodriguez',
    userImage: '/images/testimonials/emma.jpg',
    rating: 5,
    title: 'A stunning piece of art!',
    content: 'The phoenix sculpture is even more beautiful in person! The detail is incredible and it\'s become a conversation starter in my living room. Definitely worth the price.',
    createdAt: '2023-03-28T00:00:00Z',
    updatedAt: '2023-03-28T00:00:00Z',
  },
]

export const mockUsers: User[] = [
  {
    id: '101',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    image: '/images/testimonials/sarah.jpg',
    role: 'user',
    createdAt: '2023-01-10T00:00:00Z',
    updatedAt: '2023-01-10T00:00:00Z',
  },
  {
    id: '102',
    name: 'Michael Chen',
    email: 'michael@example.com',
    image: '/images/testimonials/michael.jpg',
    role: 'user',
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2023-01-15T00:00:00Z',
  },
  {
    id: '103',
    name: 'Emma Rodriguez',
    email: 'emma@example.com',
    image: '/images/testimonials/emma.jpg',
    role: 'user',
    createdAt: '2023-02-01T00:00:00Z',
    updatedAt: '2023-02-01T00:00:00Z',
  },
  {
    id: '104',
    name: 'Admin User',
    email: 'admin@nsynthic.com',
    role: 'admin',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
  },
] 